# Storage Class definition for EBS
# Volume will be created in the Cloud Provider, here is AWS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage # This is just a name, but the StorageClass is created in the Coud Provider
provisioner: ebs.csi.aws.com  # Ensure the AWS EBS CSI driver is installed
parameters:
  type: gp2
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi